[package]
org = "ballerina"
name = "observe"
version = "1.1.1"
distribution = "2201.7.0"
export = ["observe", "observe.mockextension" ]

[platform.java11]
graalvmCompatible = true

[[platform.java11.dependency]]
path = "../native/build/libs/observe-native-1.1.1-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "observe"

[[platform.java11.dependency]]
groupId = "io.opentelemetry"
artifactId = "opentelemetry-sdk-trace"
version = "1.0.0"

[[platform.java11.dependency]]
groupId = "io.opentelemetry"
artifactId = "opentelemetry-sdk-testing"
version = "1.0.0"

[[platform.java11.dependency]]
groupId = "io.opentelemetry"
artifactId = "opentelemetry-sdk-common"
version = "1.0.0"

[[platform.java11.dependency]]
groupId = "io.opentelemetry"
artifactId = "opentelemetry-semconv"
version = "1.0.0-alpha"
