[package]
org = "ballerina"
name = "observe"
version = "1.2.0"
distribution = "2201.8.0"
export = ["observe", "observe.mockextension" ]

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
path = "../native/build/libs/observe-native-1.2.0-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "observe"

[[platform.java17.dependency]]
groupId = "io.opentelemetry"
artifactId = "opentelemetry-sdk-trace"
version = "1.7.0"

[[platform.java17.dependency]]
groupId = "io.opentelemetry"
artifactId = "opentelemetry-sdk-testing"
version = "1.7.0"

[[platform.java17.dependency]]
groupId = "io.opentelemetry"
artifactId = "opentelemetry-sdk-common"
version = "1.7.0"

[[platform.java17.dependency]]
groupId = "io.opentelemetry"
artifactId = "opentelemetry-semconv"
version = "1.7.0-alpha"
